#! /bin/sh

sxhkd &

bspc monitor -d web term chat code music 6 7 

bspc config border_width         3 
#bspc config window_gap           37 
bspc config window_gap           2 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color \#000000

#bspc desktop ^1 -l monocle
bspc desktop ^1 -l tiled

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Google-chrome desktop=^1
bspc rule -a Firefox desktop=^1
bspc rule -a Firefox-esr desktop=^1
bspc rule -a Terminator desktop=^2
bspc rule -a rxvt-unicode desktop=^2
bspc rule -a rxvt desktop=^2
bspc rule -a URxvt desktop=^2
bspc rule -a St desktop=^2
bspc rule -a Xterm desktop=^2
bspc rule -a Genymotion desktop=^3
bspc rule -a TelegramDesktop desktop=^3
bspc rule -a Subl desktop=^4
bspc rule -a Spotify desktop=^5
bspc rule -a Pithos desktop=^5
bspc rule -a Lmms desktop=^5
bspc rule -a mplayer2 state=floating
bspc rule -a Gedit state=floating
bspc rule -a Eog state=floating
bspc rule -a Nautilus state=floating
bspc rule -a File-roller state=floating
bspc rule -a Gnome-system-monitor state=floating

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config super mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
bspc config click_to_focus true
#bspc config focus_follows_pointer true

# bspc config presel_feedback_color \#aaaaaa
bspc config presel_feedback_color \#ffffff

xsetroot -cursor_name left_ptr
 
#feh --bg-fill "/home/gamehelp16/Pictures/unsplashwall.jpg"
#feh --bg-fill ~/Pictures/zF1V6EE.jpg 
#feh --randomize --bg-fill ~/Pictures/dark
#gnome-wallpaper-changer &
compton --config ~/.config/compton.conf -b
xrdb -merge ~/.Xdefaults
redshift &
#/home/gamehelp16/allfloat.sh &

#panel &
polybar top &

